/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
import Logica.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan
 */
public class Juego extends javax.swing.JFrame {
    
    private Cuentas sistemaCuentas;
    private Usuario usuarioActual;

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        setSize(750, 800);
        setLocationRelativeTo(null);
    }
    
    public Juego(Cuentas sistema, Usuario usuario) {
        this.sistemaCuentas = sistema;
        this.usuarioActual = usuario;
        initComponents();
        setSize(750, 800);
        setLocationRelativeTo(null);
        setTitle("HEROES STRATEGO - " + usuario.getUsuario());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Partida = new javax.swing.JButton();
        perfil = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        configurar = new javax.swing.JButton();
        universom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Partida.setBackground(new java.awt.Color(204, 204, 204));
        Partida.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Partida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-control-48.png"))); // NOI18N
        Partida.setText("Partida Nueva");
        Partida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Partida.setOpaque(true);
        Partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidaActionPerformed(evt);
            }
        });
        getContentPane().add(Partida);
        Partida.setBounds(250, 260, 240, 70);

        perfil.setBackground(new java.awt.Color(204, 204, 204));
        perfil.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-masculino-en-círculo-48.png"))); // NOI18N
        perfil.setText("Mi Perfil");
        perfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        getContentPane().add(perfil);
        perfil.setBounds(250, 420, 240, 70);

        cerrarsesion.setBackground(new java.awt.Color(204, 204, 204));
        cerrarsesion.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        cerrarsesion.setText("Cerrar Sesión");
        cerrarsesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarsesion);
        cerrarsesion.setBounds(250, 580, 240, 70);

        configurar.setBackground(new java.awt.Color(204, 204, 204));
        configurar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        configurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ajustes-48.png"))); // NOI18N
        configurar.setText("Configuración");
        configurar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(configurar);
        configurar.setBounds(250, 340, 240, 70);

        universom.setBackground(new java.awt.Color(204, 204, 204));
        universom.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        universom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        universom.setText("Universo Marvel");
        universom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(universom);
        universom.setBounds(250, 500, 240, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stra.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, 0, 880, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        new Perfil(sistemaCuentas, usuarioActual).setVisible(true);
        dispose();
    }//GEN-LAST:event_perfilActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro que desea cerrar sesión?",
            "Confirmar Cierre de Sesión",
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, 
                "¡Hasta luego, " + usuarioActual.getUsuario() + "!", 
                "Sesión Cerrada", JOptionPane.INFORMATION_MESSAGE);
            new Proyecto2_1(sistemaCuentas).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void PartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Partida;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JButton configurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton perfil;
    private javax.swing.JButton universom;
    // End of variables declaration//GEN-END:variables
}
