/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import Logica.Cuentas;
import Logica.Usuario;
import javax.swing.JOptionPane;
 
/**
 *
 * @author Nathan
 */
public class Registro extends javax.swing.JFrame {

    private Cuentas sistemaCuentas;
    private static final int max_U = 100;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setSize(750,800);
        setLocationRelativeTo(null);
        this.sistemaCuentas = new Cuentas(); 

    }
    public Registro(Cuentas sistema) {
        initComponents();
        setSize(750, 800);
        setLocationRelativeTo(null);
        this.sistemaCuentas = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ingresu = new javax.swing.JTextField();
        ingresc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        jLabel2.setText("Usuario:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 250, 260, 50);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        jLabel3.setText("Contraseña:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 320, 260, 50);

        ingresu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresuActionPerformed(evt);
            }
        });
        getContentPane().add(ingresu);
        ingresu.setBounds(370, 250, 290, 50);
        getContentPane().add(ingresc);
        ingresc.setBounds(370, 320, 290, 50);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-registro-50.png"))); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 450, 250, 60);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 450, 250, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stra.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-130, 0, 1360, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String usuarioIngresado = ingresu.getText();
        String contraIngresada = ingresc.getText();
        
        if (usuarioIngresado == null || usuarioIngresado.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, ingresa tu nombre de usuario.", 
                "Usuario Requerido", 
                JOptionPane.WARNING_MESSAGE);
            ingresu.requestFocus();
            return;
        }
        
        if (contraIngresada == null || contraIngresada.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, ingresa tu contraseña.", 
                "Contraseña Requerida", 
                JOptionPane.WARNING_MESSAGE);
            ingresc.requestFocus();
            return;
        }
        
        usuarioIngresado = usuarioIngresado.trim();
        contraIngresada = contraIngresada.trim();
        
        if (sistemaCuentas == null) {
            sistemaCuentas = new Cuentas(); 
            JOptionPane.showMessageDialog(this, 
                "No hay usuarios registrados en el sistema.\n" +
                "Por favor, crea una cuenta primero.", 
                "Sin Usuarios Registrados", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if (sistemaCuentas.verificarCredenciales(usuarioIngresado, contraIngresada)) {
            
            Usuario usuarioLoggeado = sistemaCuentas.buscarUsuario(usuarioIngresado);
            
            JOptionPane.showMessageDialog(this, 
                "¡Bienvenido, " + usuarioIngresado + "!\n" +
                "Inicio de sesión exitoso.", 
                "Bienvenido", 
                JOptionPane.INFORMATION_MESSAGE);
            
            ingresu.setText("");
            ingresc.setText("");
            
            new Juego(sistemaCuentas, usuarioLoggeado).setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "Usuario o contraseña incorrectos.\n\n" +
                "Verifica que:\n" +
                "• El nombre de usuario sea exacto\n" +
                "• La contraseña tenga exactamente 5 caracteres\n" +
                "• Hayas creado una cuenta previamente", 
                "Error de Inicio de Sesión", 
                JOptionPane.ERROR_MESSAGE);
            
            ingresc.setText("");
            ingresc.requestFocus();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Proyecto2_1(sistemaCuentas).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresc;
    private javax.swing.JTextField ingresu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
